.ifndef __ALPHABET_INDEXES_INC__
.define __ALPHABET_INDEXES_INC__

.define alphabetTiles.0 0
.define alphabetTiles.1 9
.define alphabetTiles.2 14
.define alphabetTiles.3 23
.define alphabetTiles.4 32
.define alphabetTiles.5 39
.define alphabetTiles.6 48
.define alphabetTiles.7 56
.define alphabetTiles.8 64
.define alphabetTiles.9 71
.define alphabetTiles.10 79
.define alphabetTiles.11 80
.define alphabetTiles.12 86
.define alphabetTiles.13 93
.define alphabetTiles.14 101
.define alphabetTiles.15 107
.define alphabetTiles.16 114
.define alphabetTiles.17 120
.define alphabetTiles.18 128
.define alphabetTiles.19 133
.define alphabetTiles.20 137
.define alphabetTiles.21 144
.define alphabetTiles.22 153
.define alphabetTiles.23 158
.define alphabetTiles.24 165
.define alphabetTiles.25 173
.define alphabetTiles.26 179
.define alphabetTiles.27 187
.define alphabetTiles.28 195
.define alphabetTiles.29 202
.define alphabetTiles.30 210
.define alphabetTiles.31 215
.define alphabetTiles.32 220
.define alphabetTiles.33 227
.define alphabetTiles.34 234
.define alphabetTiles.35 241
.define alphabetTiles.36 249
.define alphabetTiles.37 258
.define alphabetTiles.38 265
.define alphabetTiles.39 270
.define alphabetTiles.40 277
.define alphabetTiles.41 284

.endif
