.ifndef __OPENINGSPRITES_INDEXES_INC__
.define __OPENINGSPRITES_INDEXES_INC__

.define openingSpritesTiles.0 0
.define openingSpritesTiles.1 21
.define openingSpritesTiles.2 44
.define openingSpritesTiles.3 57
.define openingSpritesTiles.4 76
.define openingSpritesTiles.5 91
.define openingSpritesTiles.6 96
.define openingSpritesTiles.7 119
.define openingSpritesTiles.8 142
.define openingSpritesTiles.9 158
.define openingSpritesTiles.10 176
.define openingSpritesTiles.11 193
.define openingSpritesTiles.12 209
.define openingSpritesTiles.13 226
.define openingSpritesTiles.14 245
.define openingSpritesTiles.15 254
.define openingSpritesTiles.16 272
.define openingSpritesTiles.17 292
.define openingSpritesTiles.18 320
.define openingSpritesTiles.19 343
.define openingSpritesTiles.20 373
.define openingSpritesTiles.21 403
.define openingSpritesTiles.22 424
.define openingSpritesTiles.23 449

.endif
